In [2]:
import pyreadr
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns
import scipy.stats as stats

In [ ]:
result = pyreadr.read_r('table.b1.rda')
df = next(iter(result.values()))
df

y      x1      x2    x3    x4    x5      x6    x7      x8      x9
rownames                                                                      
1         10.0  2113.0  1985.0  38.9  64.7   4.0   868.0  59.7  2205.0  1917.0
2         11.0  2003.0  2855.0  38.8  61.3   3.0   615.0  55.0  2096.0  1575.0
3         11.0  2957.0  1737.0  40.1  60.0  14.0   914.0  65.6  1847.0  2175.0
4         13.0  2285.0  2905.0  41.6  45.3  -4.0   957.0  61.4  1903.0  2476.0
5         10.0  2971.0  1666.0  39.2  53.8  15.0   836.0  66.1  1457.0  1866.0
6         11.0  2309.0  2927.0  39.7  74.1   8.0   786.0  61.0  1848.0  2339.0
7         10.0  2528.0  2341.0  38.1  65.4  12.0   754.0  66.1  1564.0  2092.0
8         11.0  2147.0  2737.0  37.0  78.3  -1.0   761.0  58.0  1821.0  1909.0
9          4.0  1689.0  1414.0  42.1  47.6  -3.0   714.0  57.0  2577.0  2001.0
10         2.0  2566.0  1838.0  42.3  54.2  -1.0   797.0  58.9  2476.0  2254.0
11         7.0  2363.0  1480.0  37.3  48.0  19.0   984.0  67.5  1984.0  2217.0
12        10.0  2109.0  2191.0  39.5  51.9   6.0   700.0  57.2  1917.0  1758.0
13         9.0  2295.0  2229.0  37.4  53.6  -5.0  1037.0  58.8  1761.0  2032.0
14         9.0  1932.0  2204.0  35.1  71.4   3.0   986.0  58.6  1709.0  2025.0
15         6.0  2213.0  2140.0  38.8  58.3   6.0   819.0  59.2  1901.0  1686.0
16         5.0  1722.0  1730.0  36.6  52.6 -19.0   791.0  54.4  2288.0  1835.0
17         5.0  1498.0  2072.0  35.3  59.3  -5.0   776.0  49.6  2072.0  1914.0
18         5.0  1873.0  2929.0  41.1  55.3  10.0   789.0  54.3  2861.0  2496.0
19         6.0  2118.0  2268.0  38.2  69.6   6.0   582.0  58.7  2411.0  2670.0
20         4.0  1775.0  1983.0  39.3  78.3   7.0   901.0  51.7  2289.0  2202.0
21         3.0  1904.0  1792.0  39.7  38.1  -9.0   734.0  61.9  2203.0  1988.0
22         3.0  1929.0  1606.0  39.7  68.8 -21.0   627.0  52.7  2592.0  2324.0
23         4.0  2080.0  1492.0  35.5  68.8  -8.0   722.0  57.8  2053.0  2550.0
24        10.0  2301.0  2835.0  35.3  74.1   2.0   683.0  59.7  1979.0  2110.0
25         6.0  2040.0  2416.0  38.7  50.0   0.0   576.0  54.9  2048.0  2628.0
26         8.0  2447.0  1638.0  39.9  57.1  -8.0   848.0  65.3  1786.0  1776.0
27         2.0  1416.0  2649.0  37.4  56.3 -22.0   684.0  43.8  2876.0  2524.0
28         0.0  1503.0  1503.0  39.3  47.0  -9.0   875.0  53.5  2560.0  2241.0

a. Fit a multiple linear regression model relating the number of games won to the team’s passing yardage (x2), the percentage of rushing plays (x7), and the opponents’ yards rushing (x8).


In [4]:
X = df[['x2', 'x7', 'x8']]
Y = df['y']
X = sm.add_constant(X)
model = sm.OLS(Y, X).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.786
Model:                            OLS   Adj. R-squared:                  0.760
Method:                 Least Squares   F-statistic:                     29.44
Date:                Sat, 22 Mar 2025   Prob (F-statistic):           3.27e-08
Time:                        08:56:13   Log-Likelihood:                -52.532
No. Observations:                  28   AIC:                             113.1
Df Residuals:                      24   BIC:                             118.4
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.8084      7.901     -0.229      0.8

In [5]:
import numpy.linalg as linalg

XtX = X.T @ X
inv_XtX = linalg.inv(XtX)
inv_XtXXt = inv_XtX @ X.T
beta_hat = inv_XtXXt @ Y
print(XtX)
print(inv_XtX)
print(inv_XtXXt)


b = np.matmul(inv_XtXXt, Y)
print(b)

         const           x2          x7           x8
const     28.0      59562.0     1628.40      59084.0
x2     59562.0  133427294.0  3449653.60  125432833.0
x7      1628.4    3449653.6    95487.38    3399712.5
x8     59084.0  125432833.0  3399712.50  128284292.0
[[ 2.14421900e+01 -9.10845877e-04 -2.27778068e-01 -2.94861063e-03]
 [-9.10845877e-04  1.65916001e-07  6.71348800e-06  7.93641577e-08]
 [-2.27778068e-01  6.71348800e-06  2.67415750e-03  2.74747659e-05]
 [-2.94861063e-03  7.93641577e-08  2.74747659e-05  5.60119508e-07]]
rownames         1         2         3         4         5         6  \
0        -0.465876  0.133643 -0.528274 -0.800597  0.572465 -0.567351   
1        -0.000006  0.000098 -0.000036  0.000134 -0.000075  0.000131   
2         0.005777 -0.003945  0.010054  0.008202  0.000199  0.005769   
3         0.000084 -0.000037  0.000026  0.000035 -0.000184 -0.000005   

rownames         7         8         9        10  ...        19        20  \
0        -0.357858  0.368657

In [6]:
print(beta_hat)

0   -1.808372
1    0.003598
2    0.193960
3   -0.004815
dtype: float64


b. Construct the analysis-of-variance table and test for significance of regression.


In [7]:
b0 = -1.8084
b2 = 0.0036
b7 = 0.1940
b8 = -0.0048

In [8]:
#Degree of freedom
n = len(df)
df_x1 = 3
df_err = len(df) - 4
df_total = len(df) - 1
print(df_x1, df_err, df_total)

3 24 27


In [9]:
#Sum of Squares
SSR = sum(((b0 + b2*df['x2'] + b7*df['x7'] + b8*df['x8']) - np.mean(df['y']))**2)
SSE = sum((df['y'] - (b0 + b2*df['x2'] + b7*df['x7'] + b8*df['x8']))**2)
SSTO = sum((df['y'] - np.mean(df['y']))**2)
print(SSR, SSE, SSTO)

256.4616671428571 69.91360999999996 326.9642857142857


In [10]:
#Mean Squares
MSR = SSR / df_x1
MSE = SSE / df_err
print(MSR, MSE)

85.48722238095236 2.9130670833333316


$$H0:\beta_0=\beta_2=\beta_7=\beta_8=0$$
$$Ha: \text{all betas are not 0}$$

In [ ]:
#Test for significant of regression
F_star = (SSR/3)/(SSE/(n-4))
print("F* = " + str(F_star))
F = stats.f.ppf(q = 1-0.05, dfn=1, dfd = n-4)
p = 1- stats.f.cdf(x = F_star, dfn=1, dfd = n-4)
print(F,F_star, p)

F* = 29.34612212332989
4.2596772726902286 29.34612212332989 1.4507727300827611e-05


**Conclusion:** F* > F so we conclude Ha, which means that the model is significant

c. Calculate t statistics for testing the hypotheses H0: 𝛽2 = 0, H0: 𝛽7 = 0, and H0: 𝛽8 = 0. What conclusions can you draw about the roles the variables x2, x7, and x8 play in the model?


In [12]:
var_covar_matrix = MSE*(inv_XtX)

s_b2 = np.sqrt(var_covar_matrix[1,1])
s_b7 = np.sqrt(var_covar_matrix[2,2])
s_b8 = np.sqrt(var_covar_matrix[3,3])

t2_star = b2/s_b2
t7_star = b7/s_b7
t8_star = b8/s_b8

print("t2* = " + str(t2_star))
print("t7* = " + str(t7_star))
print("t8* = " + str(t8_star))

t2* = 5.178251296935467
t7* = 2.19802686377778
t8* = -3.757730633812456


In [13]:
t_val = stats.t.ppf(q = 1-0.05/2, df=n-4)
print("t = " + str(t_val))

t = 2.0638985616280205


**Conclusion:**  
- |t2*| > t so we conclude $$Ha:\beta2\neq0$$
- |t7*| > t so we conclude $$Ha:\beta7\neq0$$
- |t8*| > t so we conclude $$Ha:\beta8\neq0$$  
Therefore, x2, x7 and x8 play a significant role in the model

d. $$\text{Calculate } R^2 \text{ and } R_a^2 \text{ for this model}$$


In [14]:
coef_determination = SSR/SSTO
ad_coef_determination = 1 - (1-coef_determination)*(n-1)/(n-4)
print ("Adjusted R^2 = " + str(ad_coef_determination))
print ("R^2 = " + str(coef_determination))

Adjusted R^2 = 0.7574186253413434
R^2 = 0.7843721114145275


e. Using the partial F test, determine the contribution of x7 to the model. How is this partial F statistic related to the t test for β7 calculated in part c above?  
$$H_0: x_7 = 0$$
$$H_a: x_7\neq0$$

In [17]:
x_reduce_raw = df[['x2', 'x8']]
x_reduce = np.hstack((np.ones((n,1)), x_reduce_raw))
XtX_reduce = x_reduce.T @ x_reduce
inv_XtX_reduce = linalg.inv(XtX_reduce)
beta_hat_reduce = inv_XtX_reduce @ x_reduce.T @ Y
y_hat_reduce = x_reduce @ beta_hat_reduce
residuals_reduce = Y - y_hat_reduce
SSE_reduce = sum(residuals_reduce**2)

q = 1
p = X.shape[1]
F_partial = ((SSE_reduce - SSE)/(q))/(SSE/(n-p))
threshold = stats.f.ppf(q = 1-0.05, dfn=q, dfd=n-p)
print(F_partial, threshold)

4.814371397967966 4.2596772726902286


**Conclusion:** F* > F so we conclude Ha, which mean x7 plays a significant role in the model

f. Find a 95% CI on β7.


In [ ]:
L = b7 - t_val * s_b7
U = b7 + t_val * s_b7
print(L, U)

0.011838295084497241 0.37616170491550277


g. Find a 95% CI on the mean number of games won by a team when 𝑥2 = 2300, 𝑥7 = 56.0, and 𝑥8 = 2100.

In [ ]:
x0 = np.array([1, 2300, 56, 2100])
y_mean = b0 + b2*2300 + b7*56 + b8*2100
t_val = stats.t.ppf(q = 1 - 0.05/2, df=df_err)
s_y = np.sqrt(MSE*(x0.dot(inv_XtX).dot(x0.T)))

L_ymean = y_mean - t_val * s_y
U_ymean = y_mean + t_val * s_y
print(L_ymean, U_ymean)

6.475135513942363 8.03606448605764
